  
version: '3'
services:
  web:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - '80:3000'
    volumes:
    - ./app:/code
    - /code/node_modules
    links:
    - "db:database"
    environment:
      MONGODB_USERNAME: username
      MONGODB_PASSWORD: password
      MONGODB_URL: database
      MONGODB_PORT: database
      MONGODB_DATABASE: experiments
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password

