version: "3"
services:
    web:
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - ./:/code/
            - /code/node_modules
        links:
            - "db:database"
        environment:
            MONGODB_URL: mongodb://username:password@database:27017
            MONGODB_DATABASE: experiments
            AUTH_SIGN_KEY_URI: https://grizzly-bear.eu.auth0.com/.well-known/jwks.json
            AUTH_AUDIENCE: http://www.grizzlybear-experiments.com
            AUTH_DOMAIN: https://grizzly-bear.eu.auth0.com/
    db:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
