apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiments
  labels:
    app: experiments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: experiments
  template:
    metadata:
      labels:
        app: experiments
    spec:
      containers:
        - name: experiments
          image: XXXX
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 8080
          # Database Configuration
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: experiments-db-secret
                  key: MONGODB_URL
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: experiments-db-secret
                  key: MONGODB_DATABASE
            # Auth0 Configuration
            - name: AUTH_SIGN_KEY_URI
              valueFrom:
                configMapKeyRef:
                  name: experiments-config-map
                  key: AUTH_SIGN_KEY_URI
            - name: AUTH_AUDIENCE
              valueFrom:
                  configMapKeyRef:
                    name: experiments-config-map
                    key: AUTH_AUDIENCE
            - name: AUTH_DOMAIN
              valueFrom:
                  configMapKeyRef:
                    name: experiments-config-map
                    key: AUTH_DOMAIN
            # Auth0 Management API Configuration
            - name: AUTH_MANAGEMENT_DOMAIN
              valueFrom:
                  secretKeyRef:
                    name: experiments-auth-management-api-secret
                    key: AUTH_MANAGEMENT_DOMAIN
            - name: AUTH_CLIENT_ID
              valueFrom:
                  secretKeyRef:
                    name: experiments-auth-management-api-secret
                    key: AUTH_CLIENT_ID
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                  secretKeyRef:
                    name: experiments-auth-management-api-secret
                    key: AUTH_CLIENT_SECRET