apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiments
  labels:
    app: experiments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: experiments
  template:
    metadata:
      labels:
        app: experiments
    spec:
      containers:
        - name: experiments
          image: XXXX
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: experiments-db-secret
                  key: MONGODB_URL
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: experiments-db-secret
                  key: MONGODB_DATABASE
