apiVersion: apps/v1
kind: Deployment
metadata:
  name: experiments-deployment
  labels:
    app: experiments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: experiments
  template:
    metadata:
      labels:
        app: experiments
    spec:
      containers:
      - name: experiments
        image: XXXX
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MONGODB_URL
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MONGODB_DATABASE
        resources:
          limits:
            memory: "1024Mi"
            cpu: "400m"