apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "public-experiments-ingress"
  namespace: "default"
  annotations:
    networking.gke.io/managed-certificates: experiments-api-certificate
    kubernetes.io/ingress.global-static-ip-name: experiments-api
spec:
  backend:
    serviceName: "public-experiments"
    servicePort: 80