apiVersion: "extensions/v1beta1"
kind: "Ingress"
metadata:
  name: "app-ingress"
  namespace: "default"
  annotations:
    networking.gke.io/managed-certificates: "elecular-app"
    kubernetes.io/ingress.global-static-ip-name: "elecular-app"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: "public-experiments"
          servicePort: 3000
    host: "experiments.api.elecular.com"
  - http:
      paths:
      - backend:
          serviceName: "user-activity"
          servicePort: 3000
    host: "user-activity.api.elecular.com"
  - http:
      paths:
      - backend:
          serviceName: "dashboard"
          servicePort: 3000
    host: "app.elecular.com"