apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - public_service.yml
  - private_service.yml
configMapGenerator:
  - name: env
    literals:
      - env=dev
