apiVersion: "v1"
kind: "Service"
metadata:
  name: "public-experiments"
  namespace: "default"
  labels:
    app: "experiments"
spec:
  ports:
    - protocol: "TCP"
      targetPort: 80
  selector:
    app: "experiments"
  type: "ClusterIP"